name: Lint Files

on:
  - push
  - pull_request

jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run textlint '**/**.md'
